"""EXPERIMENTAL — `horus capabilities`: a read-only fleet capability catalog.

Agents keep asking "what can project X do, and where in the code?" Hand-written
docs answering that rot the moment the project moves. This module instead
GENERATES a structured, queryable index from sources the fleet already
maintains as truth — no second source of truth, no hand-authored prose:

- each registered project's ``.horus/PRD.md`` ``## Shipped`` ledger (one line
  per capability, per the PRD skeleton contract) — best-effort for the older
  six-lane ``features.md`` layout too;
- that same PRD's ``## Shipped`` answers "what can it do?" but nothing captures
  "what IS it?" — a ``vision`` field carries a one-line frame reduced from the
  ``## Vision`` section's lead sentence (see ``vision_lead``), so an
  orientation-critical fact that lives only there (not in any Shipped bullet)
  isn't capability-invisible;
- for CLI-type projects, the actual code surface: the argparse subcommand
  tree. v1 implements only harness's own `horus` CLI as the exemplar; the
  extractor registry (``_CLI_EXTRACTORS``) is where a web(routes)/lib
  (entry-points) extractor would plug in later.

A capability entry may carry ``related_commands`` — a cheap, substring-based
cross-reference to CLI commands the Shipped line itself mentions (e.g. a line
containing `` `horus fleet` `` links to the ``horus fleet`` command).

v2 adds a **per-project, self-documenting mode** (``--project <name>``, or the
default when run from inside a registered project): it regenerates the same
kind of record for just that one project and writes a provenance-stamped copy
to ``<project>/.horus/capabilities.json`` (also printed to stdout, pipeable).
See ``generate_project`` for the one deliberate relaxation of the idempotence
invariant below.

Invariants (mirrors the `horus wiki` spike's read-model contract — this module
does not depend on that unmerged branch; it owns its own copy of the small
markdown-section parser it needs):

- **Read-only** over every source ``.horus/`` file; the only writes are the
  generated catalog file(s) themselves.
- **No second source of truth.** Every generated file carries a "generated —
  do not edit" note and is meant to be regenerated, never hand-edited.
- **Idempotent — fleet catalog.** Output is a pure function of the source
  files: no timestamps, deterministic ordering, stable text — re-running
  yields no diff. The per-project record relaxes this ONE way, by design: its
  provenance stamp (``generated_at``) is fresh every run; the ``project``
  payload underneath it stays just as idempotent as the fleet catalog.
- **No fetching.** Reads local checkouts only; remote freshness is out of scope.
- **Self-contained.** Does not touch or wire into any existing command's behavior.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from horus import __version__, config, frontmatter, markdown, routines

NOTE = (
    "Generated by `horus capabilities` — do not edit; regenerate from source "
    "`.horus/` files instead."
)

SCHEMA_VERSION = 1

# Top-level markdown list item: `- `, `* `, or `1. ` (leading indent tolerated so a
# section that starts sub-bulleted still yields items). We keep only the top level.
_LIST_ITEM_RE = re.compile(r"^(\s*)(?:[-*]|\d+\.)\s+(.*\S)\s*$")


def default_out_path() -> Path:
    return config.config_dir() / "capabilities.json"


@dataclass
class Capability:
    """One Shipped-ledger entry, plus any cheap cross-reference found in it."""

    text: str
    related_commands: list[str] = field(default_factory=list)


@dataclass
class CliCommand:
    """One node in an extracted CLI subcommand tree."""

    command: str  # full invocation, e.g. "horus config workspace-root"
    help: str


@dataclass
class ProjectCatalog:
    name: str
    path: str
    layer: str  # "prd" | "six-lane" | "none"
    vision: str | None = None  # one-line "what IS it" frame from `## Vision`; None if absent
    capabilities: list[Capability] = field(default_factory=list)
    cli_surface: list[CliCommand] | None = None  # None: no extractor for this project


# ---------------------------------------------------------------------------
# Shipped-ledger extraction (PRD v3)
# ---------------------------------------------------------------------------


def _section(body: str, heading: str) -> str:
    """Body of a top-level ``## <heading>`` section, until the next ``## `` heading.

    Case-insensitive and tolerant of a trailing qualifier, so
    ``## Shipped (details in git)`` still matches ``Shipped``. Returns "" when
    the section is absent.
    """
    lines = body.splitlines()
    target = heading.casefold()
    start = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("## "):
            continue
        head = stripped[3:].strip().casefold()
        if head == target or head.startswith(target + " "):
            start = i + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for i in range(start, len(lines)):
        if lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def _top_level_items(section_body: str) -> list[str]:
    """Text of each *top-level* list item in a section (bullets or numbers).

    Falls back to bold-paragraph items when there are no list markers at all —
    this repo's own live PRD writes ``## Shipped`` as ``**Title:** …`` blocks,
    not bullets. Folds continuation lines (indented or nested content after a
    top-level marker) into the item text, collapsing whitespace.
    """
    lines = section_body.splitlines()

    # First pass: identify all list markers and their indentation.
    markers: list[tuple[int, int, str]] = []  # (line_num, indent, text_after_marker)
    for i, line in enumerate(lines):
        m = _LIST_ITEM_RE.match(line)
        if m:
            indent = len(m.group(1))
            text = m.group(2)
            markers.append((i, indent, text))

    if not markers:
        return _bold_paragraph_items(section_body)

    base_indent = min(indent for _, indent, _ in markers)

    # Second pass: collect top-level items with their continuation lines.
    items: list[str] = []
    for idx, (marker_line_num, marker_indent, marker_text) in enumerate(markers):
        if marker_indent != base_indent:
            # Skip non-top-level markers; they fold into their parent.
            continue

        # Start with the marker line text.
        text_parts = [" ".join(marker_text.split())]

        # Find where this item ends: at the next top-level (or shallower) marker
        # or end of section. This skips nested markers, which will be included.
        next_marker_line = len(lines)
        for j in range(idx + 1, len(markers)):
            next_indent = markers[j][1]
            if next_indent <= base_indent:
                next_marker_line = markers[j][0]
                break

        # Collect continuation lines and nested items: all non-empty lines until
        # the next top-level marker. Nested items (deeper indent) are folded in.
        for i in range(marker_line_num + 1, next_marker_line):
            line = lines[i]
            m = _LIST_ITEM_RE.match(line)
            if m:
                # A list marker: include it if nested (deeper indent).
                marker_indent_here = len(m.group(1))
                if marker_indent_here > base_indent:
                    text_parts.append(" ".join(m.group(2).split()))
            else:
                # Not a list marker: include if non-empty (continuation line).
                stripped = line.strip()
                if stripped:
                    text_parts.append(stripped)

        items.append(" ".join(text_parts))

    return items


def _bold_paragraph_items(section_body: str) -> list[str]:
    """Fallback item extractor for ``**Title:** …`` paragraph-style entries.

    A new item begins at each line that starts with ``**``; following
    non-bold, non-empty lines fold into it (wrapped continuation).
    """
    items: list[str] = []
    current: list[str] = []
    for raw in section_body.splitlines():
        stripped = raw.strip()
        if stripped.startswith("**"):
            if current:
                items.append(" ".join(current))
            current = [stripped]
        elif current and stripped:
            current.append(stripped)
    if current:
        items.append(" ".join(current))
    return items


def shipped_lines(prd_body: str) -> list[str]:
    """One-line-per-capability entries from a PRD's ``## Shipped`` section."""
    return _top_level_items(_section(prd_body, "Shipped"))


def six_lane_shipped_lines(features_text: str) -> list[str]:
    """Best-effort Shipped-equivalent entries from an older six-lane ``features.md``."""
    return routines.feature_items(features_text)["shipped"]


def vision_lead(body: str) -> str | None:
    """A short one-line "what IS it" frame from a ``## Vision`` section: its lead
    sentence (or opening bold lead line), markdown-stripped — NOT the whole
    section. This is the orientation fact the Shipped ledger can't carry (e.g.
    "Claude Code as the runtime, no app to deploy"), not a vision summary.
    ``None`` when the section is absent or empty."""
    section = _section(body, "Vision")
    if not section.strip():
        return None
    lead = markdown.first_sentence(markdown.plain_text(section))
    return lead or None


# ---------------------------------------------------------------------------
# CLI-surface extraction — pluggable by project name; only argparse implemented.
# ---------------------------------------------------------------------------


def _walk_argparse(parser: argparse.ArgumentParser, prefix: tuple[str, ...]) -> list[CliCommand]:
    """Recursively walk an argparse parser's subcommand tree.

    Uses argparse's internal ``_SubParsersAction``/``_choices_actions`` to
    recover each subcommand's declared ``help=`` text — there is no public API
    for this, but the shape is stable across supported Python versions.
    """
    out: list[CliCommand] = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        helps = {choice.dest: (choice.help or "") for choice in action._choices_actions}
        for name, subparser in action.choices.items():
            path = prefix + (name,)
            out.append(CliCommand(command=" ".join(path), help=helps.get(name, "")))
            out.extend(_walk_argparse(subparser, path))
    return out


def _horus_own_cli_surface() -> list[CliCommand]:
    from horus import cli as horus_cli

    return _walk_argparse(horus_cli.build_parser(), ("horus",))


# Extractor registry keyed by project name — a stand-in for a real project-type
# detector until a second (web routes / lib entry-points) extractor exists. v1
# only covers harness's own argparse CLI, introspected in-process (no
# subprocess/--help scraping needed since we import the parser directly).
_CLI_EXTRACTORS: dict[str, Callable[[], list[CliCommand]]] = {
    "horus-harness": _horus_own_cli_surface,
}


def cli_surface_for(project_name: str) -> list[CliCommand] | None:
    extractor = _CLI_EXTRACTORS.get(project_name)
    return extractor() if extractor else None


# ---------------------------------------------------------------------------
# Cross-referencing (cheap, substring-based — no NLP)
# ---------------------------------------------------------------------------


def _mention_pattern(phrase: str) -> re.Pattern[str]:
    """Whole-token match for a command phrase: forbids an adjacent word/hyphen
    char so "horus run" doesn't match inside "horus run-something-else"."""
    return re.compile(rf"(?<![\w-]){re.escape(phrase)}(?![\w-])")


def _related_commands(text: str, commands: list[CliCommand]) -> list[str]:
    return sorted({cmd.command for cmd in commands if _mention_pattern(cmd.command).search(text)})


# ---------------------------------------------------------------------------
# Aggregation (pure — text in, data out; easy to unit-test on fixture text)
# ---------------------------------------------------------------------------


def build_project_catalog(
    name: str, path: str, prd_text: str | None, features_text: str | None
) -> ProjectCatalog:
    """Build one project's catalog entry from its already-read source text.

    ``prd_text`` wins when present (v3 layout); otherwise ``features_text`` is
    used best-effort (v2 six-lane layout); otherwise the project is recorded
    with no extracted capabilities.
    """
    commands = cli_surface_for(name)
    if prd_text is not None:
        body = frontmatter.parse(prd_text).body
        lines = shipped_lines(body)
        vision = vision_lead(body)
        layer = "prd"
    elif features_text is not None:
        lines = six_lane_shipped_lines(features_text)
        vision = vision_lead(features_text)  # best-effort; six-lane rarely has `## Vision`
        layer = "six-lane"
    else:
        lines = []
        vision = None
        layer = "none"
    capabilities = [
        Capability(text=line, related_commands=_related_commands(line, commands or []))
        for line in lines
    ]
    return ProjectCatalog(
        name=name, path=path, layer=layer, vision=vision, capabilities=capabilities, cli_surface=commands
    )


def _read_project_sources(root: Path) -> tuple[str | None, str | None]:
    """The already-read PRD / six-lane ``features.md`` text for ``root``, or
    ``(None, None)`` when neither is present."""
    prd_path = frontmatter.prd_path(root)
    prd_text = prd_path.read_text(encoding="utf-8") if prd_path.is_file() else None
    features_path = root / ".horus" / "features.md"
    features_text = (
        features_path.read_text(encoding="utf-8")
        if prd_text is None and features_path.is_file()
        else None
    )
    return prd_text, features_text


def load_catalog(project_paths: list[str]) -> list[ProjectCatalog]:
    """Read the registry into per-project catalogs. Read-only; skips paths
    whose ``.horus/`` is gone. Sorted by name for deterministic output."""
    catalogs: list[ProjectCatalog] = []
    for path_str in project_paths:
        root = Path(path_str)
        if not (root / ".horus").is_dir():
            continue
        prd_text, features_text = _read_project_sources(root)
        catalogs.append(build_project_catalog(root.name, root.as_posix(), prd_text, features_text))
    catalogs.sort(key=lambda c: c.name.casefold())
    return catalogs


def load_project_catalog(path_str: str) -> ProjectCatalog:
    """Build ONE project's live catalog straight from its ``.horus/`` sources.

    Unlike ``load_catalog``, never skips a project outright — a registered
    project missing its ``.horus/`` dir still yields a ``layer="none"`` record
    rather than silently disappearing, since this is the sole record for that
    one project, not an entry in a fleet-wide list.
    """
    root = Path(path_str)
    prd_text = features_text = None
    if (root / ".horus").is_dir():
        prd_text, features_text = _read_project_sources(root)
    return build_project_catalog(root.name, root.as_posix(), prd_text, features_text)


# ---------------------------------------------------------------------------
# Per-project resolution — resolve a registered project by directory basename.
# ---------------------------------------------------------------------------


def resolve_project_path(name: str, project_paths: list[str]) -> str | None:
    """The registered path whose directory basename is ``name``, or ``None``."""
    for path_str in project_paths:
        if Path(path_str).name == name:
            return path_str
    return None


def project_path_for_cwd(cwd: Path, project_paths: list[str]) -> str | None:
    """The registered path matching ``cwd`` exactly — the self-document default
    (run with no ``--project`` from inside a registered project's root)."""
    resolved = cwd.resolve()
    for path_str in project_paths:
        if Path(path_str).resolve() == resolved:
            return path_str
    return None


# ---------------------------------------------------------------------------
# Serialization + generation (the only I/O; writes ONLY the output file)
# ---------------------------------------------------------------------------


def _catalog_to_dict(c: ProjectCatalog) -> dict:
    return {
        "name": c.name,
        "path": c.path,
        "layer": c.layer,
        "vision": c.vision,
        "capabilities": [asdict(cap) for cap in c.capabilities],
        "cli_surface": [asdict(cmd) for cmd in c.cli_surface] if c.cli_surface is not None else None,
    }


def to_dict(catalogs: list[ProjectCatalog]) -> dict:
    return {
        "note": NOTE,
        "schema_version": SCHEMA_VERSION,
        "projects": [_catalog_to_dict(c) for c in catalogs],
    }


def render_json(catalogs: list[ProjectCatalog]) -> str:
    """Deterministic JSON text: stable key/list ordering, no timestamps — two
    runs over the same sources produce byte-identical output."""
    return json.dumps(to_dict(catalogs), indent=2) + "\n"


def generate(project_paths: list[str], out_path: Path) -> str:
    """Build the fleet-wide catalog and write it to ``out_path``. Returns the
    rendered JSON text. Read-only over every source; the only write is
    ``out_path``. Idempotent — no timestamps, so an unchanged run performs no
    write (this is the fleet-wide catalog; the per-project record below is
    deliberately NOT idempotent — see ``generate_project``)."""
    text = render_json(load_catalog(project_paths))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if not out_path.exists() or out_path.read_text(encoding="utf-8") != text:
        out_path.write_text(text, encoding="utf-8")
    return text


# ---------------------------------------------------------------------------
# Per-project, self-documenting mode — a stamped, provenance-carrying record
# for ONE project, written to that project's own `.horus/capabilities.json`.
#
# This relaxes the fleet-wide "idempotent (no timestamps)" invariant by
# design: the record is regenerated fresh on every invocation (never a stale
# stored copy the caller trusts back) and carries a `generated_at` stamp that
# is expected to differ run over run, while the `project` payload underneath
# stays a pure function of the source `.horus/` files, just like the fleet
# catalog.
# ---------------------------------------------------------------------------


def project_out_path(path_str: str) -> Path:
    return Path(path_str) / ".horus" / "capabilities.json"


def render_project_json(catalog: ProjectCatalog) -> str:
    payload = {
        "note": NOTE,
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "horus_version": __version__,
        "project": _catalog_to_dict(catalog),
    }
    return json.dumps(payload, indent=2) + "\n"


def generate_project(path_str: str, out_path: Path | None = None) -> str:
    """Regenerate ONE project's stamped capability record from its LIVE
    ``.horus/`` sources and write it to ``out_path`` (default:
    ``<project>/.horus/capabilities.json``). Returns the rendered JSON text.

    Always rewrites, unlike ``generate`` — the stamp changes every run by
    design; this is a fresh provenance-stamped artifact, not a cache to be
    read back."""
    text = render_project_json(load_project_catalog(path_str))
    out = out_path if out_path is not None else project_out_path(path_str)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return text
