"""EXPERIMENTAL — `horus wiki`: a read-only fleet-memory read-model.

A *projection* of the fleet's continuity, never a second store. Git-backed
`.horus/` files stay the single source of truth; this module reads them and emits
a derived Obsidian-compatible vault so the fleet can be browsed as a linked graph.

Invariants (see the spike PR / PRD backlog item for the reasoning):

- **Read-only** over every source `.horus/` file. This module opens files for
  reading only; it never writes back into any project's `.horus/`.
- **No second source of truth.** Generated notes carry a "generated — do not edit"
  banner and are meant to be regenerated, never hand-edited.
- **Idempotent.** Output is a pure function of the source files: no generation
  timestamps, deterministic ordering, stable text — re-running yields no diff.
- **No fetching.** It reads local checkouts only; remote freshness is out of scope.
- **Self-contained.** A new, clearly-experimental subcommand that does not touch or
  wire into any existing command's behavior.

Structure of the emitted vault (default ``~/.horus/wiki/``)::

    <out>/
      index.md                 map-of-content: every project as a [[wikilink]]
      projects/<name>.md       one note per registered project

Obsidian resolves ``[[name]]`` to ``projects/name.md`` anywhere in the vault, so
project→project edges render as a graph out of the box.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from horus import config, frontmatter

# The banner stamped at the top of every generated note. Intentionally carries no
# timestamp — a timestamp would break idempotence (re-running would diff).
BANNER = (
    "> [!warning] Generated by `horus wiki` — do not edit.\n"
    "> This is a read-only projection of git-backed `.horus/` continuity.\n"
    "> Edits are lost on regeneration; change the source `.horus/PRD.md` instead.\n"
)

# Top-level markdown list item: `- `, `* `, or `1. ` (leading indent tolerated so a
# section that starts sub-bulleted still yields items). We keep only the top level.
_LIST_ITEM_RE = re.compile(r"^(\s*)(?:[-*]|\d+\.)\s+(.*\S)\s*$")

# Frontmatter keys that may carry an explicit cross-project link convention. Values
# are free-form strings (the frontmatter parser is scalar-only): comma/space lists,
# optionally `[[wikilink]]`-wrapped. Both are optional and unenforced.
_LINK_KEYS = ("related", "depends_on")


def default_out_dir() -> Path:
    return config.config_dir() / "wiki"


# ---------------------------------------------------------------------------
# Extraction (pure — easy to unit-test on fixture text)
# ---------------------------------------------------------------------------


@dataclass
class ProjectNode:
    """Everything the read-model extracts for one registered project."""

    name: str
    path: str
    has_prd: bool
    focus: dict[str, str] = field(default_factory=dict)
    backlog: list[str] = field(default_factory=list)
    shipped: list[str] = field(default_factory=list)
    rules: list[str] = field(default_factory=list)
    # target project-name -> set of reasons ("mention", "related", "depends_on").
    links: dict[str, set[str]] = field(default_factory=dict)


def _section(body: str, heading: str) -> str:
    """Body of a top-level ``## <heading>`` section, until the next ``## `` heading.

    Robust to imperfect markdown: the match is case-insensitive and tolerates a
    trailing qualifier, so ``## Rules (load-bearing)`` still matches ``Rules``.
    Returns "" when the section is absent.
    """
    lines = body.splitlines()
    target = heading.casefold()
    start = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("## "):
            continue
        head = stripped[3:].strip().casefold()
        if head == target or head.startswith(target + " "):
            start = i + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for i in range(start, len(lines)):
        if lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def _top_level_items(section_body: str) -> list[str]:
    """Text of each *top-level* list item in a section, sub-bullets excluded.

    A "top-level" item is the shallowest indent depth seen among list markers, so a
    section whose items are all indented (e.g. under a `**note:**` lead-in) still
    yields its items rather than nothing. Wrapped continuation lines (no marker) are
    ignored. Whitespace inside each item is collapsed for stable, one-line output.
    """
    matches: list[tuple[int, str]] = []
    for line in section_body.splitlines():
        m = _LIST_ITEM_RE.match(line)
        if m:
            matches.append((len(m.group(1)), " ".join(m.group(2).split())))
    if not matches:
        return _bold_paragraph_items(section_body)
    base_indent = min(indent for indent, _ in matches)
    return [text for indent, text in matches if indent == base_indent]


def _bold_paragraph_items(section_body: str) -> list[str]:
    """Fallback item extractor for sections written as ``**Title:** …`` blocks rather
    than bullets (this repo's live PRD ``## Shipped`` uses that shape).

    A new item begins at each line that starts with ``**``; following lines that do
    not start a new bold entry are folded into it. A non-bold preamble line (e.g.
    "One line per capability…") is ignored. Each item is collapsed to one line.
    """
    items: list[str] = []
    current: list[str] = []
    for raw in section_body.splitlines():
        stripped = raw.strip()
        if stripped.startswith("**"):
            if current:
                items.append(" ".join(current))
            current = [stripped]
        elif current and stripped:
            current.append(stripped)
    if current:
        items.append(" ".join(current))
    return items


def _split_link_value(raw: str) -> list[str]:
    """Parse an explicit ``related:`` / ``depends_on:`` frontmatter string into names.

    Tolerates comma- and/or whitespace-separated lists and `[[wikilink]]` wrapping,
    e.g. ``"[[horus-hub]], horus-agent"`` -> ``["horus-hub", "horus-agent"]``.
    """
    names: list[str] = []
    for token in re.split(r"[,\s]+", raw.strip()):
        token = token.strip().strip("[]").strip()
        if token:
            names.append(token)
    return names


def _mention_pattern(name: str) -> re.Pattern[str]:
    """Whole-token, case-insensitive matcher for a project name.

    Project names contain hyphens (``horus-hub``), so a plain ``\\b`` boundary would
    match inside ``horus-hub-extra``. We forbid an adjacent word char or hyphen.
    """
    return re.compile(rf"(?<![\w-]){re.escape(name)}(?![\w-])", re.IGNORECASE)


def extract_node(name: str, path: str, prd_text: str | None, focus: dict[str, str]) -> ProjectNode:
    """Build a :class:`ProjectNode` from one project's PRD text and resolved focus.

    ``prd_text`` is ``None`` for a six-lane (v2) project with no ``PRD.md``; the node
    is still emitted (best-effort) with focus fields and empty sections. Cross-project
    link detection against other registered projects is added later by
    :func:`link_nodes`, which needs the whole fleet.
    """
    node = ProjectNode(name=name, path=path, has_prd=prd_text is not None, focus=dict(focus))
    if prd_text is None:
        return node
    doc = frontmatter.parse(prd_text)
    node.backlog = _top_level_items(_section(doc.body, "Backlog"))
    node.shipped = _top_level_items(_section(doc.body, "Shipped"))
    node.rules = _top_level_items(_section(doc.body, "Rules"))
    # Explicit link convention (optional): stash raw values on the focus dict so
    # link_nodes can read them without re-parsing frontmatter.
    for key in _LINK_KEYS:
        val = doc.front_matter.get(key)
        if val:
            node.focus[f"_link:{key}"] = str(val)
    return node


def _raw_text_for_mentions(prd_text: str | None, focus: dict[str, str]) -> str:
    """Text to scan for mentions of other projects: the PRD plus focus fields (so a
    project named only in ``current_focus``/``next_prompt`` still links)."""
    parts = [prd_text or ""]
    parts += [v for k, v in focus.items() if not k.startswith("_link:")]
    return "\n".join(parts)


def link_nodes(nodes: list[ProjectNode], prd_texts: dict[str, str | None]) -> None:
    """Populate each node's ``links`` in place, two ways (both optional/best-effort):

    (a) **mentions** — another registered project's name appearing as a whole token
        anywhere in this project's PRD text or focus fields;
    (b) **explicit** — names listed in ``related:`` / ``depends_on:`` frontmatter.

    Self-links are dropped. Explicit targets are kept even if not registered (they
    render as an unresolved wikilink — still a legitimate graph node in Obsidian).
    """
    names = [n.name for n in nodes]
    patterns = {name: _mention_pattern(name) for name in names}
    for node in nodes:
        haystack = _raw_text_for_mentions(prd_texts.get(node.name), node.focus)
        for other in names:
            if other == node.name:
                continue
            if patterns[other].search(haystack):
                node.links.setdefault(other, set()).add("mention")
        for key in _LINK_KEYS:
            raw = node.focus.get(f"_link:{key}")
            if not raw:
                continue
            for target in _split_link_value(raw):
                if target and target != node.name:
                    node.links.setdefault(target, set()).add(key)


def load_nodes(project_paths: list[str]) -> list[ProjectNode]:
    """Read the registry's projects into linked :class:`ProjectNode`s. Read-only.

    Skips registered paths that no longer have a ``.horus/`` directory. Nodes are
    returned sorted by name for deterministic, idempotent downstream output.
    """
    nodes: list[ProjectNode] = []
    prd_texts: dict[str, str | None] = {}
    for path_str in project_paths:
        root = Path(path_str)
        if not (root / ".horus").is_dir():
            continue
        name = root.name
        prd_path = frontmatter.prd_path(root)
        prd_text = prd_path.read_text(encoding="utf-8") if prd_path.is_file() else None
        focus = frontmatter.resolve_focus(root)
        prd_texts[name] = prd_text
        nodes.append(extract_node(name, str(root), prd_text, focus))
    link_nodes(nodes, prd_texts)
    nodes.sort(key=lambda n: n.name.casefold())
    return nodes


# ---------------------------------------------------------------------------
# Rendering (pure text -> str; no I/O)
# ---------------------------------------------------------------------------

# How many section items to surface in a note. The full detail lives in the source
# PRD; the read-model is a browsable index, not a mirror.
_MAX_ITEMS = 12


def _bullet_block(items: list[str], empty: str) -> str:
    if not items:
        return f"_{empty}_\n"
    shown = items[:_MAX_ITEMS]
    lines = [f"- {t}" for t in shown]
    if len(items) > _MAX_ITEMS:
        lines.append(f"- _…and {len(items) - _MAX_ITEMS} more (see source PRD)._")
    return "\n".join(lines) + "\n"


def _focus_block(focus: dict[str, str]) -> str:
    rows = []
    for key in ("status", "current_focus", "next_action", "next_prompt", "execution_recommendation", "last_updated"):
        val = " ".join(str(focus.get(key, "")).split())
        if val:
            rows.append(f"- **{key.replace('_', ' ')}:** {val}")
    return "\n".join(rows) + "\n" if rows else "_No focus frontmatter._\n"


def render_project_note(node: ProjectNode) -> str:
    """Render a single project's Obsidian note (deterministic text)."""
    out = [BANNER, f"# {node.name}\n"]
    if not node.has_prd:
        out.append("> [!info] Six-lane (v2) project — best-effort: focus only, sections not extracted.\n")

    out.append("## Focus\n")
    out.append(_focus_block(node.focus))

    if node.links:
        out.append("\n## Connections\n")
        for target in sorted(node.links, key=str.casefold):
            reasons = ", ".join(sorted(node.links[target]))
            out.append(f"- [[{target}]] — _{reasons}_")
        out.append("")

    out.append("\n## Backlog\n")
    out.append(_bullet_block(node.backlog, "No backlog items extracted."))
    out.append("\n## Shipped\n")
    out.append(_bullet_block(node.shipped, "No shipped items extracted."))
    out.append("\n## Rules\n")
    out.append(_bullet_block(node.rules, "No rules extracted."))

    out.append(f"\n---\n_Source: `{node.path}/.horus/PRD.md` · projection, do not edit._\n")
    return "\n".join(out).rstrip("\n") + "\n"


def render_index(nodes: list[ProjectNode]) -> str:
    """Render the map-of-content note linking every project."""
    out = [BANNER, "# Horus Fleet — Wiki\n"]
    out.append(
        "A read-only projection of every registered project's `.horus/` continuity. "
        "Open this vault in Obsidian to browse the fleet as a linked graph.\n"
    )
    out.append(f"\n**{len(nodes)} project(s):**\n")
    for node in nodes:
        focus = " ".join(str(node.focus.get("current_focus", "")).split())
        summary = f" — {focus[:120]}" if focus else ""
        edge_count = len(node.links)
        edges = f" ({edge_count} link{'s' if edge_count != 1 else ''})" if edge_count else ""
        out.append(f"- [[{node.name}]]{edges}{summary}")
    out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Generation (the only I/O; writes ONLY into out_dir, never into any .horus/)
# ---------------------------------------------------------------------------


def generate(project_paths: list[str], out_dir: Path) -> list[Path]:
    """Generate the vault into ``out_dir``. Returns the written paths (sorted).

    Idempotent: given the same source files it writes byte-identical content, so a
    second run produces no diff. Only writes under ``out_dir``; the source `.horus/`
    trees are opened read-only.
    """
    nodes = load_nodes(project_paths)
    projects_dir = out_dir / "projects"
    projects_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    index_path = out_dir / "index.md"
    _write_if_changed(index_path, render_index(nodes))
    written.append(index_path)
    for node in nodes:
        note_path = projects_dir / f"{node.name}.md"
        _write_if_changed(note_path, render_project_note(node))
        written.append(note_path)
    return sorted(written)


def _write_if_changed(path: Path, content: str) -> None:
    """Write only when content differs — keeps mtimes stable across idempotent runs."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")
